### ISSUE TITLE
CI

### ISSUE THREAD

**Issue by florianm** [florianm/govhack2015#17]
add CI, either TravisCI or CircleCI

**Comment by Mause** [comment]
Unrelated, but it may well be worth considering doing any further work in a branch until we're sure that judging has been completed

**Comment by florianm** [comment]
Too late, too late :-) but would have been a very good idea!
I've included a disclaimer in the [docs](http://govhack2015.readthedocs.org/en/latest/) about that. There will be a requirement to progress on this setup unrelated to GovHack but a good month earlier than the national prize announcement on Sept 5.
Also, there's our write-up and the video at hackerspace as reference.

**Comment by florianm** [comment]
circleCI works, travis doesn't support docker. good enough!
